WebAPI_MyBlog/MyBlog_Clients_MVC/Controllers/AuthController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using MyBlog_Clients_MVC.Dto;
using MyBlog_Clients_MVC.Models;

namespace MyBlog_Clients_MVC.Controllers
{
    public class AuthController : Controller
    {
        private readonly HttpClient _client;
        private readonly INotyfService _notyf;

        public AuthController(INotyfService notyf)
        {
            _client = new HttpClient();
            _notyf = notyf;
        }

        public IActionResult Index()
        {
            return View();
        }


        // GET: Register
        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        // POST: Register
        [HttpPost]
        public async Task<IActionResult> Register(RegisterDto registerDto)
        {
            if (!ModelState.IsValid)
            {
                return View(registerDto);
            }

            var response = await _client.PostAsJsonAsync("https://localhost:7233/api/Auth/register", registerDto);

            if (!response.IsSuccessStatusCode)
            {
                // Đọc message từ API response
                var errorMessage = await response.Content.ReadAsStringAsync();
            
                _notyf.Warning(errorMessage);
                return View(registerDto);
            }

            // Optional: Redirect to login page after successful registration
            _notyf.Success("Register Succesfully");
            return RedirectToAction("Login");
        }

        // GET: Login
        [HttpGet]
        public async Task<IActionResult> Login()
        {
            return View();
        }

        // POST: Login
        [HttpPost]
        public async Task<IActionResult> Login(LoginDto loginDto)
        {
            if (!ModelState.IsValid)
            {
                return View(loginDto);
            }

            var response = await _client.PostAsJsonAsync("https://localhost:7233/api/Auth/login", loginDto);

            if (!response.IsSuccessStatusCode)
            {
                // Đọc message từ API response
                var errorMessage = await response.Content.ReadAsStringAsync();

                _notyf.Warning(errorMessage);
                return View(loginDto);  
            }

            var tokenData = await response.Content.ReadFromJsonAsync<TokenResponse>();
            HttpContext.Session.SetString("AccessToken", tokenData.AccessToken);
            HttpContext.Session.SetString("UserName", tokenData.UserName);


            if(tokenData.UserName == "Admin")
            {

                _notyf.Success("Login Successfully");
                return RedirectToAction("Index", "Admin");
            }

            //Optional: Redirect to a protected page after successful login
            _notyf.Success("Login Succesfully");
            return RedirectToAction("Index", "Home");
        }
    }
}

WebAPI_MyBlog/MyBlog_Clients_MVC/Controllers/PostController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using MyBlog_Clients_MVC.Dto;
using Newtonsoft.Json;

namespace MyBlog_Clients_MVC.Controllers
{
    public class PostController : Controller
    {
        private readonly HttpClient _client;
        private readonly INotyfService _notyf;

        public PostController(INotyfService notyf)
        {
            _client = new HttpClient();
            _notyf = notyf;
        }
        public IActionResult Index()
        {
            return View();
        }

        // GET: PostDetail
        [HttpGet]
        public async Task<IActionResult> PostDetail(int postId)
        {

            var token = HttpContext.Session.GetString("AccessToken");

            //lấy ra category list
            string CategoryListJson = HttpContext.Session.GetString("CategoryListJson");


            if (!string.IsNullOrEmpty(CategoryListJson))
            {
                // Giải mã JSON thành danh sách
                List<CategoryDto> CategoriesList = JsonConvert.DeserializeObject<List<CategoryDto>>(CategoryListJson);

                ViewBag.CategoriesList = CategoriesList;
            }

            //kiểm tra xem đã log in chưa
            if (token == null)
            {
                _notyf.Warning("Sign In to see post detail.");
                return RedirectToAction("Index", "Home");
            }

            var request = new HttpRequestMessage(method: HttpMethod.Get, $"https://localhost:7233/api/Post/{postId}");
            request.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);


            HttpResponseMessage response = await _client.SendAsync(request);


            if (response.StatusCode == System.Net.HttpStatusCode.NotFound)
            {
                ViewData["NotFound"] = "Not Found !";
                return View();
            }

            string strData = await response.Content.ReadAsStringAsync();
            var postDetail = JsonConvert.DeserializeObject<PostDto>(strData);

            return View(postDetail);
        }

        [HttpGet]
        public async Task<IActionResult> PostByCategory(int categoryId, string categoryName)
        {
            if(categoryName != null)
            {
                HttpContext.Session.SetString("CategoryName", categoryName);
            }

            //Get All posts
            HttpResponseMessage getAllPostResponse = await _client.GetAsync($"https://localhost:7233/api/Categories/{categoryId}/posts");
            if (getAllPostResponse.StatusCode == System.Net.HttpStatusCode.NotFound)
            {
                ViewData["NotFound"] = "Not Found !";
                return View();
            }
            string strData = await getAllPostResponse.Content.ReadAsStringAsync();
            var postsList = JsonConvert.DeserializeObject<List<PostDto>>(strData);


            //Get newest posts
            HttpResponseMessage getNewestPosts = await _client.GetAsync("https://localhost:7233/api/Post/newestPosts");
            if (getNewestPosts.StatusCode == System.Net.HttpStatusCode.NotFound)
            {
                ViewData["NotFound"] = "Not Found !";
                return View();
            }
            string strData2 = await getNewestPosts.Content.ReadAsStringAsync();
            var newestPosts = JsonConvert.DeserializeObject<List<PostDto>>(strData2);


            //Get categoriesList
            HttpResponseMessage getCategoriesResponse = await _client.GetAsync("https://localhost:7233/api/Categories");
            if (getCategoriesResponse.StatusCode == System.Net.HttpStatusCode.NotFound)
            {
                ViewData["NotFound"] = "Not Found !";
                return View();
            }
            string strData3 = await getCategoriesResponse.Content.ReadAsStringAsync();
            var categoriesList = JsonConvert.DeserializeObject<List<CategoryDto>>(strData3);



            ViewBag.PostsList = postsList;
            ViewBag.NewestPosts = newestPosts;
            ViewBag.CategoriesList = categoriesList;

            return View();
        }
    }
}

WebAPI_MyBlog/MyBlog_Clients_MVC/Views/Admin/Shared/_AdminLayout.cshtml
@{
    var accessToken = Context.Session.GetString("AccessToken");
    var userName = Context.Session.GetString("UserName");
}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - MyBlog_Clients_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyBlog_Clients_MVC.styles.css" asp-append-version="true" />
    <!-- font icons -->
    <link rel="stylesheet" href="~/assets/vendors/themify-icons/css/themify-icons.css">
    <!-- Bootstrap + JoeBLog main styles -->
    <link rel="stylesheet" href="~/assets/css/joeblog.css">
</head>
<body data-spy="scroll" data-target=".navbar" data-offset="40" id="home">
    <header>
        <!-- page First Navigation -->
        <nav class="navbar navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand">
                    <img src="~/assets/imgs/AnNguyen.svg" class="logo" style="width: 100px; height: 100px;" alt="">
                </a>
                <div class="socials">
                    <a href="javascript:void(0)"><i class="ti-facebook"></i></a>
                    <a href="javascript:void(0)"><i class="ti-twitter"></i></a>
                    <a href="javascript:void(0)"><i class="ti-pinterest-alt"></i></a>
                    <a href="javascript:void(0)"><i class="ti-instagram"></i></a>
                    <a href="javascript:void(0)"><i class="ti-youtube"></i></a>
                </div>
            </div>
        </nav>
        <!-- End Of First Navigation -->
        <!-- Page Second Navigation -->
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark rounded shadow mb-3 sticky-top">
            <div class="container">
                <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav">

                        @*                         <li class="nav-item">
                        <a class="nav-link disabled" href="#">Disabled</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="CreatePost">Create Post</a>
                        </li>
                        @foreach (var item in ViewBag.CategoriesList)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Post" asp-action="PostByCategory" asp-route-categoryName="@item.Name" asp-route-categoryId="@item.Id">@item.Name</a>
                            </li>
                        }
                    </ul>
                    @if (userName == null && string.IsNullOrEmpty(accessToken))
                    {
                        <div class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="btn btn-outline-primary" asp-controller="Auth" asp-action="Login">Sign In </a>
                            </li>

                            <li class="nav-item">
                                <a class="btn btn-outline-primary" asp-controller="Auth" asp-action="Register">Sign Up</a>
                            </li>
                        </div>
                    }
                    else
                    {
                        <div class="navbar-nav ml-auto">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="ti-heart"></i>
                                    Welcome @userName
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="#">My Profile</a>
                                    <a class="dropdown-item" href="#">Another action</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Log Out</a>
                                </div>
                            </li>
                        </div>
                    }


                </div>
            </div>
        </nav>
        <!-- End Of Page Second Navigation -->
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- Page Footer -->
    <footer class="page-footer">
        <div class="container">
            <div class="row align-items-center justify-content-between">
                <div class="col-md-3 text-center text-md-left mb-3 mb-md-0">
                    <img src="~/assets/imgs/AnNguyen.svg" class="logo" alt="">
                </div>
                <div class="col-md-9 text-center text-md-right">
                    <div class="socials">
                        <p class="font-weight-bold text-muted mr-4">
                            "Welcome to my personal space for sharing. Here, I capture my
                        </p>
                        <p class="font-weight-bold text-muted mr-4">
                            diverse thoughts, knowledge, life experiences, and journey exploring the
                        </p>
                        <p class="font-weight-bold text-muted mr-4">
                            world of technology. Thank you for visiting and being a part of this journey!"
                        </p>
                    </div>
                </div>
            </div>
            <p class="border-top mb-0 mt-4 pt-3 small">&copy; <script>document.write(new Date().getFullYear())</script>, AnNguyenBlog Created By <a href="https://www.facebook.com/annguyen3024/" class="text-muted font-weight-bold" target="_blank">Thien An.</a> </p>
        </div>
    </footer>
    <!-- End of Page Footer -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- core  -->
    <script src="~/assets/vendors/jquery/jquery-3.4.1.js"></script>
    <script src="~/assets/vendors/bootstrap/bootstrap.bundle.js"></script>

    <!-- JoeBLog js -->
    <script src="~/assets/js/joeblog.js"></script>
    @await Component.InvokeAsync("Notyf");
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>